
project_id = "dtlcprcpvdomrehbejhw"

[functions.analyze-input]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.generate-blueprint]
verify_jwt = false

[functions.generate-pdf-blueprint]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false
